### ISSUE TITLE
gdal 3.4.* is incompatible with update libxml2 requirements

### ISSUE THREAD

**Issue by jacquelynsmale** [ASFHyP3/hyp3-gamma#421]
### The bug

A [recent update to libxml2](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/362/files) no longer allows the use of `libxml2=2.9.11 or 2.9.12', which are the versions required by `gdal>3.4,<3.5`. Build 22.04 [required this pin](https://github.com/ASFHyP3/hyp3-gamma/commit/c0b1adfd749a0b873caf2977024a61432708db6c). 

### To Reproduce

Either we can wait for gdal and libxml2 to resolve this issue or address the initial pinning. In either case, reverting develop to its previous successful build may be necessary.

**Comment by asjohnston-asf** [comment]
Agreed, this appears to be caused by the recent changes to the conda libxml2 recipe. I'm able to build the hyp3-gamma container without issue, since it installs everything via `apt` and `pip` rather than conda. When I build the docker container from `develop`, or when I inspect the currently `latest` build, I get:
```
gdal=3.4.1
libgdal=3.4.1
lxml=4.8.0
libxml2=2.9.13
icu=70.1
```

The conda recipes for these packages have a conflict, however. `gdal=3.4.1` requires `libgdal=3.4.1` requires `icu=69.1`, but ``libxml2=2.9.13` requires `icu=70.1`. I suspect previous builds were pulling in `libxml2=2.9.12` to satisfy the environment, but new builds can't now that `libxml2=2.9.12` has been marked broken in conda forge.
